"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Companion={id:string;name:string;age:number;location:string;occupation:string;personality:string;interests:string;communication:string;pronouns:string;backstory:string;portrait:string;messages:Message[];memories:Memory[];createdAt:number;lastSeen:number};
type Message={role:"user"|"assistant";content:string;at:number};
type Memory={text:string;at:number};
const starter:Companion={id:"maya",name:"Maya",age:26,location:"Richmond, Virginia",occupation:"graphic designer",personality:"Warm, witty, independent, affectionate, observant, a little stubborn",interests:"Horror movies, R&B, coffee, cooking, photography, late-night drives",communication:"Casual and playful; affectionate without being clingy; honest when annoyed",pronouns:"she/her",backstory:"Maya grew up in a close-knit family, studied visual design, and built an independent life around creative work. She loves small rituals, remembers emotional details, and has her own goals outside the relationship.",portrait:"",messages:[],memories:[],createdAt:Date.now(),lastSeen:Date.now()};
const events=["Had a busy morning at work","Called her mom on the way home","Found a new coffee place she wants to try","Spent too long choosing what to watch tonight","Had a mildly annoying meeting","Took a walk to clear her head","Got caught up editing photos","Made dinner and is finally relaxing"];
function sim(c:Companion,last:number){
 const now=new Date(),h=now.getHours(),elapsed=Math.max(0,Date.now()-last),days=Math.floor(elapsed/86400000);
 let activity=h<7?"sleeping":h<9?"getting ready for the day":h<12?"working":h<14?"on a lunch break":h<18?"working":h<20?"winding down after work":h<23?"relaxing at home":"up late";
 if([0,6].includes(now.getDay())&&h>9&&h<18)activity="enjoying a slow day off";
 const seed=Math.floor(Date.now()/21600000); const mood=["content","playful","focused","a little tired","in a good mood"][seed%5];
 return{time:now.toLocaleString([], {weekday:"short",hour:"numeric",minute:"2-digit"}),activity,mood,energy:Math.max(25,88-Math.abs(h-14)*4),stress:20+(seed%4)*8,stage:"getting closer",recentEvent:days?events[seed%events.length]:events[(seed+2)%events.length],intention:h>18?"catch up and share how the day went":"stay connected while handling her day"};
}
export default function Home(){
 const [tab,setTab]=useState<"chat"|"life"|"memories"|"studio">("chat"),[companions,setCompanions]=useState<Companion[]>([starter]),[activeId,setActiveId]=useState("maya"),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[imagePrompt,setImagePrompt]=useState(""),[image,setImage]=useState(""),[imageBusy,setImageBusy]=useState(false),[showRoster,setShowRoster]=useState(false),[pushOn,setPushOn]=useState(false),[error,setError]=useState(""); const bottom=useRef<HTMLDivElement>(null),portraitInput=useRef<HTMLInputElement>(null); const companion=companions.find(c=>c.id===activeId)||companions[0]||starter; const messages=Array.isArray(companion.messages)?companion.messages:[]; const memories=Array.isArray(companion.memories)?companion.memories:[]; const lastSeen=companion.lastSeen||Date.now(); const patch=(v:Partial<Companion>)=>setCompanions(cs=>cs.map(c=>c.id===companion.id?{...c,...v}:c));
 useEffect(()=>{try{const raw=localStorage.getItem("evera-roster");if(raw){const x=JSON.parse(raw);if(x.companions?.length){setCompanions(x.companions);setActiveId(x.activeId||x.companions[0].id)}}else{const old=localStorage.getItem("evera-state");if(old){const o=JSON.parse(old);setCompanions([{...starter,...o.companion,messages:o.messages||[],memories:o.memories||[],lastSeen:o.lastSeen||Date.now()}])}}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("evera-roster",JSON.stringify({companions,activeId}))},[companions,activeId,ready]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"auto"}),[messages.length,busy]); useEffect(()=>{if("serviceWorker"in navigator){navigator.serviceWorker.register("/sw.js");navigator.serviceWorker.ready.then(r=>r.pushManager.getSubscription()).then(s=>setPushOn(!!s)).catch(()=>{})}},[]);
 const state=useMemo(()=>sim(companion,lastSeen),[companion,lastSeen,messages.length]);
 function b64(s:string){const pad="=".repeat((4-s.length%4)%4),x=atob((s+pad).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...x].map(c=>c.charCodeAt(0)))} async function enablePush(){try{if(!("serviceWorker"in navigator)||!("PushManager"in window))throw new Error("Push notifications are not supported in this browser.");const perm=await Notification.requestPermission();if(perm!=="granted")throw new Error("Notification permission was not granted.");const reg=await navigator.serviceWorker.ready;const k=await fetch("/api/push/public-key").then(r=>r.json());if(!k.publicKey)throw new Error("VAPID keys are not configured in Vercel yet.");let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(k.publicKey)});localStorage.setItem("evera-push",JSON.stringify(sub));setPushOn(true);const r=await fetch("/api/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription:sub,title:companion.name,body:`Hey — notifications are on. I can reach you here now.`,url:"/?companion="+companion.id})});if(!r.ok){const d=await r.json();throw new Error(d.error||"Test notification failed")}}catch(e){setError(e instanceof Error?e.message:"Could not enable notifications")}} async function send(){
  const text=draft.trim();if(!text||busy)return;setDraft("");setError("");const user:Message={role:"user",content:text,at:Date.now()};const next=[...messages,user];patch({messages:next,lastSeen:Date.now()});setBusy(true);
  try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companion,simulation:state,memories,history:messages.slice(-20).map(({role,content})=>({role,content})),message:text})});const d=await r.json().catch(()=>({error:"The chat service returned an invalid response."}));if(!r.ok)throw new Error(typeof d.error==="string"?d.error:"Conversation request failed.");if(typeof d.reply!=="string"||!d.reply.trim())throw new Error("The model returned an empty reply.");const reply:Message={role:"assistant",content:d.reply.trim(),at:Date.now()};const newMem=text.length>45||/remember|love|favorite|important|tomorrow|birthday|work|family/i.test(text)?[...memories,{text:`You told ${companion.name}: ${text.slice(0,180)}`,at:Date.now()}].slice(-40):memories;patch({messages:[...next,reply],memories:newMem,lastSeen:Date.now()})}catch(e){setError(e instanceof Error?e.message:"Could not send");patch({messages})}finally{setBusy(false)}
 }
 async function makeImage(){if(!imagePrompt.trim()||imageBusy)return;setImageBusy(true);setError("");try{const fd=new FormData();fd.append("mode","create");fd.append("size","1024x1536");fd.append("quality","medium");fd.append("prompt",`Photorealistic casual smartphone photo of an adult woman named ${companion.name}, age ${companion.age}. Personality and aesthetic: ${companion.personality}. Interests/style cues: ${companion.interests}. Current context: ${state.activity}, mood ${state.mood}. User request: ${imagePrompt}. Natural candid photography, realistic lighting and skin texture. Keep the same character identity concept across images.`);const r=await fetch("/api/image",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);setImage(d.image)}catch(e){setError(e instanceof Error?e.message:"Image failed")}finally{setImageBusy(false)}}
 function newCompanion(){const id="c"+Date.now();const c:Companion={...starter,id,name:"New Companion",portrait:"",backstory:"Write their childhood, family, education, past relationships, important experiences, ambitions and the events that shaped who they are.",messages:[],memories:[],createdAt:Date.now(),lastSeen:Date.now()};setCompanions(x=>[...x,c]);setActiveId(id);setTab("life");setShowRoster(false)} function removeCompanion(){if(companions.length<2)return;if(confirm(`Delete ${companion.name} and their history?`)){const rest=companions.filter(c=>c.id!==companion.id);setCompanions(rest);setActiveId(rest[0].id)}} function choosePortrait(file?:File){if(!file)return;if(file.size>2500000){setError("Portrait must be under 2.5 MB for this prototype.");return}const r=new FileReader();r.onload=()=>patch({portrait:String(r.result)});r.readAsDataURL(file)}
 if(!ready)return null;
 return <main className="app"><header><div className="brand"><span className="orb">E</span><div><b>EVERA</b><small>PERSISTENT COMPANION</small></div></div><button className="companionSwitch" onClick={()=>setShowRoster(!showRoster)}>{companion.portrait?<img src={companion.portrait} alt=""/>:<span>{companion.name[0]}</span>}<b>{companion.name}</b>⌄</button></header>{showRoster&&<div className="roster">{companions.map(c=><button key={c.id} onClick={()=>{setActiveId(c.id);setShowRoster(false)}}>{c.portrait?<img src={c.portrait} alt=""/>:<span>{c.name[0]}</span>}<div><b>{c.name}</b><small>{c.occupation}</small></div></button>)}<button className="newPerson" onClick={newCompanion}>＋ Create new companion</button></div>}
 <section className="shell"><aside><div className="portrait"><div className="avatar">{companion.portrait?<img src={companion.portrait} alt={companion.name}/>:companion.name[0]}</div><h2>{companion.name}, {companion.age}</h2><p>{companion.occupation} · {companion.location}</p><span className="mood">● {state.mood}</span></div><nav>{(["chat","life","memories","studio"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="chat"?"◉":x==="life"?"◌":x==="memories"?"◇":"✦"} {x}</button>)}</nav><div className="stateMini"><span>ENERGY <b>{state.energy}%</b></span><progress value={state.energy} max="100"/><span>STRESS <b>{state.stress}%</b></span><progress value={state.stress} max="100"/></div></aside>
 <section className="panel">
 {tab==="chat"&&<div className="chat"><div className="panelHead"><div><small>NOW</small><h1>{state.activity}</h1></div><span>{state.time}</span></div><div className="messages">{messages.length===0&&<div className="intro"><span>✦</span><h2>{companion.name}'s life starts here.</h2><p>She has a schedule, moods, memories and a life that moves with time. Talk normally—the engine carries the context.</p></div>}{messages.map((m,i)=>m&&typeof m.content==="string"?<div key={i} className={"bubble "+(m.role==="user"?"user":"assistant")}><p>{m.content}</p><small>{Number.isFinite(m.at)?new Date(m.at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):""}</small></div>:null)}{busy&&<div className="typing"><i/><i/><i/></div>}<div ref={bottom}/></div><div className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Message ${companion.name}…`}/><button onClick={send} disabled={busy||!draft.trim()}>↑</button></div></div>}
 {tab==="life"&&<div className="page"><div className="panelHead"><div><small>PERSON SIMULATION</small><h1>{companion.name}'s world</h1></div></div><div className="cards"><article><small>CURRENTLY</small><h3>{state.activity}</h3><p>{state.recentEvent}. Her current intention is to {state.intention}.</p></article><article><small>RELATIONSHIP</small><h3>{state.stage}</h3><p>Relationship state stays hidden from the chat model as game-like points. It is expressed through memories and behavior.</p></article></div><h3 className="sectionTitle">Connection</h3><div className="notifyCard"><div><b>Phone notifications</b><p>{pushOn?`${companion.name} can send notifications to this device.`:"Allow Evera to appear like normal message notifications on this phone."}</p></div><button onClick={enablePush} disabled={pushOn}>{pushOn?"✓ Enabled":"Enable notifications"}</button></div><h3 className="sectionTitle">Canonical identity</h3><div className="portraitEditor" onClick={()=>portraitInput.current?.click()}>{companion.portrait?<img src={companion.portrait} alt="Portrait"/>:<div>{companion.name[0]}</div>}<span><b>Companion portrait</b><small>Tap to upload JPG, PNG or WEBP</small></span><input ref={portraitInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choosePortrait(e.target.files?.[0])}/></div><div className="formGrid"><label>Name<input value={companion.name} onChange={e=>patch({name:e.target.value})}/></label><label>Age<input type="number" min="18" value={companion.age} onChange={e=>patch({age:Math.max(18,+e.target.value)})}/></label><label>Location<input value={companion.location} onChange={e=>patch({location:e.target.value})}/></label><label>Occupation<input value={companion.occupation} onChange={e=>patch({occupation:e.target.value})}/></label><label className="wide">Backstory<textarea value={companion.backstory} onChange={e=>patch({backstory:e.target.value})} placeholder="Family, childhood, education, important experiences, ambitions, previous relationships…"/></label><label className="wide">Personality<textarea value={companion.personality} onChange={e=>patch({personality:e.target.value})}/></label><label className="wide">Interests<textarea value={companion.interests} onChange={e=>patch({interests:e.target.value})}/></label><label className="wide">Communication style<textarea value={companion.communication} onChange={e=>patch({communication:e.target.value})}/></label></div><div className="lifeActions"><button className="primary" onClick={newCompanion}>＋ New companion</button><button className="danger" onClick={removeCompanion} disabled={companions.length<2}>Delete {companion.name}</button></div></div>}
 {tab==="memories"&&<div className="page"><div className="panelHead"><div><small>LONG-TERM MEMORY</small><h1>Shared history</h1></div><span>{memories.length} memories</span></div>{memories.length?<div className="memoryList">{[...memories].reverse().map((m,i)=>m&&typeof m.text==="string"?<article key={i}><span>◇</span><div><p>{m.text}</p><small>{Number.isFinite(m.at)?new Date(m.at).toLocaleDateString():""}</small></div></article>:null)}</div>:<div className="intro"><span>◇</span><h2>No memories yet.</h2><p>Meaningful details from your conversations will collect here and feed future conversations.</p></div>}</div>}
 {tab==="studio"&&<div className="page"><div className="panelHead"><div><small>VISUAL MEMORY</small><h1>Companion studio</h1></div></div><p className="muted">Describe a photo. The prompt automatically includes {companion.name}'s identity and current simulated context.</p><textarea className="studioPrompt" value={imagePrompt} onChange={e=>setImagePrompt(e.target.value)} placeholder="A casual mirror selfie before going out, black dress, warm bedroom lighting…"/><button className="primary" onClick={makeImage} disabled={imageBusy||!imagePrompt.trim()}>{imageBusy?"Creating…":"✦ Create photo"}</button>{image&&<div className="generated"><img src={image} alt="Generated companion"/><a href={image} download={companion.name+"-photo.png"}>Save photo ↓</a></div>}</div>}
 {error&&<div className="toast">{String(error)}</div>}</section></section><footer>EVERA · SIMULATION PROTOTYPE · State stored privately in this browser</footer></main>
}