"use client";
import {useRef,useState} from "react";
export default function Home(){
 const [mode,setMode]=useState<"create"|"edit">("create"),[prompt,setPrompt]=useState(""),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[result,setResult]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""); const input=useRef<HTMLInputElement>(null);
 function choose(f?:File){if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setMode("edit");setResult("");}
 async function run(){setError("");setBusy(true);try{const fd=new FormData();fd.append("mode",mode);fd.append("prompt",prompt);fd.append("size",(document.getElementById("size") as HTMLSelectElement).value);fd.append("quality",(document.getElementById("quality") as HTMLSelectElement).value);if(file)fd.append("image",file);const r=await fetch("/api/image",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");setResult(d.image)}catch(e){setError(e instanceof Error?e.message:"Something went wrong")}finally{setBusy(false)}}
 return <main><header><div className="brand"><span className="mark">✦</span><div><b>FORGE</b><small>AI IMAGE STUDIO</small></div></div><span className="pill">PRIVATE STUDIO</span></header>
 <section className="hero"><p className="eyebrow">CREATE WITHOUT LIMITS</p><h1>Turn ideas into<br/><em>images.</em></h1><p>Generate original visuals from words or transform your own photos with natural-language edits.</p></section>
 <div className="tabs"><button className={mode==="create"?"active":""} onClick={()=>setMode("create")}>✦ Create</button><button className={mode==="edit"?"active":""} onClick={()=>setMode("edit")}>◫ Edit image</button></div>
 <section className="workspace">
  {mode==="edit"&&<div className="upload" onClick={()=>input.current?.click()}>{preview?<img src={preview} alt="upload preview"/>:<><strong>Drop or choose an image</strong><span>PNG, JPG or WEBP</span></>}<input ref={input} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0])}/></div>}
  <label>{mode==="create"?"WHAT DO YOU WANT TO CREATE?":"HOW SHOULD I CHANGE IT?"}</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={mode==="create"?"A cinematic portrait in neon rain, shallow depth of field...":"Keep the subject the same, replace the background with a snowy mountain at sunrise..."}/>
  <div className="controls"><div><label>FORMAT</label><select id="size" defaultValue="1024x1024"><option value="1024x1024">Square · 1:1</option><option value="1536x1024">Landscape · 3:2</option><option value="1024x1536">Portrait · 2:3</option></select></div><div><label>QUALITY</label><select id="quality" defaultValue="medium"><option value="low">Draft</option><option value="medium">Standard</option><option value="high">High</option></select></div></div>
  <button className="generate" disabled={busy||!prompt.trim()||(mode==="edit"&&!file)} onClick={run}>{busy?<><i/>Creating…</>:mode==="create"?"✦ Generate image":"✦ Apply edit"}</button>{error&&<p className="error">{error}</p>}
 </section>
 <section className={"result "+(result?"show":"")}>{result?<><div className="resultHead"><div><span>RESULT</span><b>Your image is ready</b></div><a href={result} download="forge-image.png">↓ Save</a></div><img src={result} alt="AI result"/><button className="secondary" onClick={()=>{setPreview(result);setMode("edit");fetch(result).then(r=>r.blob()).then(b=>setFile(new File([b],"forge.png",{type:"image/png"})));window.scrollTo({top:0,behavior:"smooth"})}}>Edit this image →</button></>:<div className="empty"><span>✦</span><b>Your creation will appear here</b><p>Write a prompt above and bring it to life.</p></div>}</section>
 <footer>FORGE AI STUDIO <span>•</span> Powered by your private API key</footer></main>}
