"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Companion={name:string;age:number;location:string;occupation:string;personality:string;interests:string;communication:string;pronouns:string};
type Message={role:"user"|"assistant";content:string;at:number};
type Memory={text:string;at:number};
const starter:Companion={name:"Maya",age:26,location:"Richmond, Virginia",occupation:"graphic designer",personality:"Warm, witty, independent, affectionate, observant, a little stubborn",interests:"Horror movies, R&B, coffee, cooking, photography, late-night drives",communication:"Casual and playful; affectionate without being clingy; honest when annoyed",pronouns:"she/her"};
const events=["Had a busy morning at work","Called her mom on the way home","Found a new coffee place she wants to try","Spent too long choosing what to watch tonight","Had a mildly annoying meeting","Took a walk to clear her head","Got caught up editing photos","Made dinner and is finally relaxing"];
function sim(c:Companion,last:number){
 const now=new Date(),h=now.getHours(),elapsed=Math.max(0,Date.now()-last),days=Math.floor(elapsed/86400000);
 let activity=h<7?"sleeping":h<9?"getting ready for the day":h<12?"working":h<14?"on a lunch break":h<18?"working":h<20?"winding down after work":h<23?"relaxing at home":"up late";
 if([0,6].includes(now.getDay())&&h>9&&h<18)activity="enjoying a slow day off";
 const seed=Math.floor(Date.now()/21600000); const mood=["content","playful","focused","a little tired","in a good mood"][seed%5];
 return{time:now.toLocaleString([], {weekday:"short",hour:"numeric",minute:"2-digit"}),activity,mood,energy:Math.max(25,88-Math.abs(h-14)*4),stress:20+(seed%4)*8,stage:"getting closer",recentEvent:days?events[seed%events.length]:events[(seed+2)%events.length],intention:h>18?"catch up and share how the day went":"stay connected while handling her day"};
}
export default function Home(){
 const [tab,setTab]=useState<"chat"|"life"|"memories"|"studio">("chat"),[companion,setCompanion]=useState(starter),[messages,setMessages]=useState<Message[]>([]),[memories,setMemories]=useState<Memory[]>([]),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[lastSeen,setLastSeen]=useState(Date.now()),[imagePrompt,setImagePrompt]=useState(""),[image,setImage]=useState(""),[imageBusy,setImageBusy]=useState(false),[error,setError]=useState(""); const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem("evera-state");if(raw){const s=JSON.parse(raw);setCompanion(s.companion||starter);setMessages(s.messages||[]);setMemories(s.memories||[]);setLastSeen(s.lastSeen||Date.now())}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("evera-state",JSON.stringify({companion,messages,memories,lastSeen:Date.now()}))},[companion,messages,memories,ready]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages,busy]);
 const state=useMemo(()=>sim(companion,lastSeen),[companion,lastSeen,messages.length]);
 async function send(){
  const text=draft.trim();if(!text||busy)return;setDraft("");setError("");const user:Message={role:"user",content:text,at:Date.now()};const next=[...messages,user];setMessages(next);setBusy(true);
  try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({companion,simulation:state,memories,history:messages.slice(-20).map(({role,content})=>({role,content})),message:text})});const d=await r.json();if(!r.ok)throw new Error(d.error);const reply:Message={role:"assistant",content:d.reply,at:Date.now()};setMessages([...next,reply]);if(text.length>45||/remember|love|favorite|important|tomorrow|birthday|work|family/i.test(text)){setMemories(m=>[...m,{text:`You told ${companion.name}: ${text.slice(0,180)}`,at:Date.now()}].slice(-40))}}catch(e){setError(e instanceof Error?e.message:"Could not send");setMessages(messages)}finally{setBusy(false)}
 }
 async function makeImage(){if(!imagePrompt.trim()||imageBusy)return;setImageBusy(true);setError("");try{const fd=new FormData();fd.append("mode","create");fd.append("size","1024x1536");fd.append("quality","medium");fd.append("prompt",`Photorealistic casual smartphone photo of an adult woman named ${companion.name}, age ${companion.age}. Personality and aesthetic: ${companion.personality}. Interests/style cues: ${companion.interests}. Current context: ${state.activity}, mood ${state.mood}. User request: ${imagePrompt}. Natural candid photography, realistic lighting and skin texture. Keep the same character identity concept across images.`);const r=await fetch("/api/image",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);setImage(d.image)}catch(e){setError(e instanceof Error?e.message:"Image failed")}finally{setImageBusy(false)}}
 function reset(){if(confirm("Reset this companion and all local memories?")){localStorage.removeItem("evera-state");setCompanion(starter);setMessages([]);setMemories([])}}
 if(!ready)return null;
 return <main className="app"><header><div className="brand"><span className="orb">E</span><div><b>EVERA</b><small>PERSISTENT COMPANION</small></div></div><div className="status"><i/> {companion.name} · {state.activity}</div></header>
 <section className="shell"><aside><div className="portrait"><div className="avatar">{companion.name[0]}</div><h2>{companion.name}, {companion.age}</h2><p>{companion.occupation} · {companion.location}</p><span className="mood">● {state.mood}</span></div><nav>{(["chat","life","memories","studio"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="chat"?"◉":x==="life"?"◌":x==="memories"?"◇":"✦"} {x}</button>)}</nav><div className="stateMini"><span>ENERGY <b>{state.energy}%</b></span><progress value={state.energy} max="100"/><span>STRESS <b>{state.stress}%</b></span><progress value={state.stress} max="100"/></div></aside>
 <section className="panel">
 {tab==="chat"&&<div className="chat"><div className="panelHead"><div><small>NOW</small><h1>{state.activity}</h1></div><span>{state.time}</span></div><div className="messages">{messages.length===0&&<div className="intro"><span>✦</span><h2>{companion.name}'s life starts here.</h2><p>She has a schedule, moods, memories and a life that moves with time. Talk normally—the engine carries the context.</p></div>}{messages.map((m,i)=><div key={i} className={"bubble "+m.role}><p>{m.content}</p><small>{new Date(m.at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</small></div>)}{busy&&<div className="typing"><i/><i/><i/></div>}<div ref={bottom}/></div><div className="composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Message ${companion.name}…`}/><button onClick={send} disabled={busy||!draft.trim()}>↑</button></div></div>}
 {tab==="life"&&<div className="page"><div className="panelHead"><div><small>PERSON SIMULATION</small><h1>{companion.name}'s world</h1></div></div><div className="cards"><article><small>CURRENTLY</small><h3>{state.activity}</h3><p>{state.recentEvent}. Her current intention is to {state.intention}.</p></article><article><small>RELATIONSHIP</small><h3>{state.stage}</h3><p>Relationship state stays hidden from the chat model as game-like points. It is expressed through memories and behavior.</p></article></div><h3 className="sectionTitle">Canonical identity</h3><div className="formGrid"><label>Name<input value={companion.name} onChange={e=>setCompanion({...companion,name:e.target.value})}/></label><label>Age<input type="number" min="18" value={companion.age} onChange={e=>setCompanion({...companion,age:Math.max(18,+e.target.value)})}/></label><label>Location<input value={companion.location} onChange={e=>setCompanion({...companion,location:e.target.value})}/></label><label>Occupation<input value={companion.occupation} onChange={e=>setCompanion({...companion,occupation:e.target.value})}/></label><label className="wide">Personality<textarea value={companion.personality} onChange={e=>setCompanion({...companion,personality:e.target.value})}/></label><label className="wide">Interests<textarea value={companion.interests} onChange={e=>setCompanion({...companion,interests:e.target.value})}/></label><label className="wide">Communication style<textarea value={companion.communication} onChange={e=>setCompanion({...companion,communication:e.target.value})}/></label></div><button className="danger" onClick={reset}>Reset simulation</button></div>}
 {tab==="memories"&&<div className="page"><div className="panelHead"><div><small>LONG-TERM MEMORY</small><h1>Shared history</h1></div><span>{memories.length} memories</span></div>{memories.length?<div className="memoryList">{[...memories].reverse().map((m,i)=><article key={i}><span>◇</span><div><p>{m.text}</p><small>{new Date(m.at).toLocaleDateString()}</small></div></article>)}</div>:<div className="intro"><span>◇</span><h2>No memories yet.</h2><p>Meaningful details from your conversations will collect here and feed future conversations.</p></div>}</div>}
 {tab==="studio"&&<div className="page"><div className="panelHead"><div><small>VISUAL MEMORY</small><h1>Companion studio</h1></div></div><p className="muted">Describe a photo. The prompt automatically includes {companion.name}'s identity and current simulated context.</p><textarea className="studioPrompt" value={imagePrompt} onChange={e=>setImagePrompt(e.target.value)} placeholder="A casual mirror selfie before going out, black dress, warm bedroom lighting…"/><button className="primary" onClick={makeImage} disabled={imageBusy||!imagePrompt.trim()}>{imageBusy?"Creating…":"✦ Create photo"}</button>{image&&<div className="generated"><img src={image} alt="Generated companion"/><a href={image} download={companion.name+"-photo.png"}>Save photo ↓</a></div>}</div>}
 {error&&<div className="toast">{error}</div>}</section></section><footer>EVERA · SIMULATION PROTOTYPE · State stored privately in this browser</footer></main>
}